name: 'Terraform Security Scan'

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  devsecops_scan:
    name: 'Security & Validation'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Format Check
        run: terraform fmt -check

      - name: Terraform Validate
        run: terraform validate

      - name: Install tfsec
        run: |
          wget https://github.com/aquasecurity/tfsec/releases/download/v1.28.14/tfsec-linux-amd64
          sudo mv tfsec-linux-amd64 /usr/local/bin/tfsec
          sudo chmod +x /usr/local/bin/tfsec

      - name: Run tfsec Security Scan
        run: tfsec .
